run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - gocritic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - commentFormatting
      - commentedOutCode
      - whyNoLint